name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Vivel
      run: dotnet build --no-restore ./Vivel
    - name: Build Vivel.Model
      run: dotnet build --no-restore ./Vivel.Model
    - name: Build Vivel.Identity
      run: dotnet build --no-restore ./Vivel.Identity
    - name: Format
      run: dotnet format --no-restore --verify-no-changes
